---
- hosts: all
  become: true
  tasks:

    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # optional: avoid updating every run

    - name: Install Apache2
      apt:
        name: apache2
        state: latest

    - name: Install PHP module for Apache
      apt:
        name: libapache2-mod-php
        state: latest

    - name: Ensure Apache is started and enabled
      service:
        name: apache2
        state: started
        enabled: true
